// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqvhmqqlbtohyitqvhxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdmhtcXFsYnRvaHlpdHF2aHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMDYzMjQsImV4cCI6MjA1MjU4MjMyNH0.3Keqw--pXWmdhG4VowCMGACTSCNrlgAAh-3LcmVrfeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);