// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyewantsdayffjyqclwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95ZXdhbnRzZGF5ZmZqeXFjbHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5ODU0NjEsImV4cCI6MjA1MzU2MTQ2MX0.MvXyWrl1qNGOWADhRNcpaYdRkPbyGOuYVaFYOI6Ktmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);